# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_abastecimento_valor_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_gasto',
            field=models.DecimalField(decimal_places=2, default='100,00', max_digits=5),
        ),
    ]
